### PR TITLE
fix: token renewal operation failed due to timeout

### PR DESCRIPTION
**Pull request by stuarthallows**
When requesting a token for an endpoint, the console errors with _ERROR Token renewal operation failed due to timeout_.
Resolved by downgrading to adal-angular 1.0.15.

See #47

### CODE REVIEW

**Comment by ringodotnl** [comment]
This also fixed our issue, cheers

**Comment by benbaran** [comment]
It was merged today : )

**Comment by DanaEpp** [comment]
Awesomeness. Thanks Ben!

**Comment by shijinmk2006** [comment]
Am facing the same issue while acquiring token. Using adal-angular4 : "4.0.12" .Still it generate the adal-angular:1.0.17 . How can i degrade to 1.0.15 at this time. While am using this Token timeout occurs eventually am not able to click on any links as i got unauthorized.In the token timeout there is a logic to set authenticated=false.

Any update on this?

**Pull request merged**
